-- Probe: the idempotency key is unique, and the database is what enforces it.
--
-- Replace the body of this file with two INSERT statements that place the same
-- order twice, carrying the same idempotency key both times. Everything else
-- about the second row may differ: a different primary key, a different
-- quantity, a different timestamp. Only the idempotency key has to repeat.
--
-- The harness wraps this file in BEGIN and ROLLBACK, so it leaves nothing
-- behind, and it runs after the seed data has loaded, so you may reference the
-- accounts and instruments from seed/ rather than creating them here.
--
-- The harness expects the second statement to fail with SQLSTATE 23505, unique
-- violation. Any other outcome is a finding:
--
--   both inserts succeed        there is no unique constraint on the key
--   23503, foreign key          the row references a parent that is not loaded
--   23502, not null             a required column is missing from the insert
--   42703, undefined column     a column name here does not match your schema
--
-- This is the constraint that stops a retried request from buying twice. It is
-- worth proving rather than assuming.

-- Write your two inserts below.
