package com.tradingsystem.spring_boot_app.config;

import io.swagger.v3.oas.models.Components;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.security.SecurityRequirement;
import io.swagger.v3.oas.models.security.SecurityScheme;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * OpenAPI document generated by springdoc from the controllers at runtime.
 * Swagger UI is served at /swagger-ui and the raw JSON at /api-docs
 * (see application.properties). Every /api/v1 route requires the access
 * token issued by the Auth Service, so the bearer scheme applies globally.
 */
@Configuration
public class OpenApiConfig {

    private static final String BEARER_SCHEME = "bearerAuth";

    @Bean
    public OpenAPI tradeApiOpenApi() {
        return new OpenAPI()
                .info(new Info()
                        .title("Trade REST API")
                        .description("Accounts, orders, instruments and watchlists for the Enterprise Trading Platform")
                        .version("1.0"))
                .components(new Components().addSecuritySchemes(BEARER_SCHEME,
                        new SecurityScheme()
                                .type(SecurityScheme.Type.HTTP)
                                .scheme("bearer")
                                .bearerFormat("JWT")))
                .addSecurityItem(new SecurityRequirement().addList(BEARER_SCHEME));
    }
}
